Fix install script
Was causing an error on install:
> PY_SRC = f'{PY_NAME}.py' % PY_NAME
> TypeError: not all arguments converted during string formatting